"""added addon table

Revision ID: 2cf30827cb34
Revises: 412771c4f878
Create Date: 2021-07-08 16:16:31.463696

"""
from alembic import op
import sqlalchemy as sa
import dbo_models

# revision identifiers, used by Alembic.
revision = '2cf30827cb34'
down_revision = '412771c4f878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addon',
    sa.Column('addon_group_id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['addon_group_id'], ['addon-group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addon_addon_group_id'), 'addon', ['addon_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_addon_addon_group_id'), table_name='addon')
    op.drop_table('addon')
    # ### end Alembic commands ###
