"""added addon group

Revision ID: 412771c4f878
Revises: a23e8e6d0268
Create Date: 2021-07-05 11:58:23.099743

"""
from alembic import op
import sqlalchemy as sa
import dbo_models


# revision identifiers, used by Alembic.
revision = '412771c4f878'
down_revision = 'a23e8e6d0268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addon-group',
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addon-group')
    # ### end Alembic commands ###
