"""added menu item to addon group

Revision ID: 9c5af6b6721a
Revises: 2cf30827cb34
Create Date: 2021-07-09 16:59:49.680227

"""
from alembic import op
import sqlalchemy as sa
import dbo_models


# revision identifiers, used by Alembic.
revision = '9c5af6b6721a'
down_revision = '2cf30827cb34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu-item-to-addon-group',
    sa.Column('menu_item_id', dbo_models._helper.GUID(), nullable=False),
    sa.Column('addon_group_id', dbo_models._helper.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['addon_group_id'], ['addon-group.id'], ),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu-item.id'], ),
    sa.PrimaryKeyConstraint('menu_item_id', 'addon_group_id')
    )
    op.create_index(op.f('ix_menu-item-to-addon-group_addon_group_id'), 'menu-item-to-addon-group', ['addon_group_id'], unique=False)
    op.create_index(op.f('ix_menu-item-to-addon-group_menu_item_id'), 'menu-item-to-addon-group', ['menu_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu-item-to-addon-group_menu_item_id'), table_name='menu-item-to-addon-group')
    op.drop_index(op.f('ix_menu-item-to-addon-group_addon_group_id'), table_name='menu-item-to-addon-group')
    op.drop_table('menu-item-to-addon-group')
    # ### end Alembic commands ###
