"""added category.py table

Revision ID: a18823406e78
Revises: 
Create Date: 2021-06-15 17:06:36.861235

"""
from alembic import op
import sqlalchemy as sa
import dbo_models

# revision identifiers, used by Alembic.
revision = 'a18823406e78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category.py',
                    sa.Column('id', dbo_models._helper.GUID(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
                    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('index', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category.py')
    # ### end Alembic commands ###
